version: '3.9'
services:
  tf:
    container_name: tf
    image: devsbaraus/tf:latest
    build: .
    command: bash
    privileged: true
    volumes:
      - .:/app
    ports:
      - 2022:22
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]